# -*- coding: utf-8 -*-
"""ASM2_GROUP 1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IO0rFDM4oaAywKJH2JaJ99bd4MVVK-OK
"""

import json
from google.colab import files
uploaded = files.upload()

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from matplotlib.pyplot import figure
import seaborn as sns
import plotly.express as px
import plotly.graph_objs as go
from IPython.display import display


# Đặt số lượng dòng hiển thị là 50
pd.options.display.max_rows = 50

# Đường dẫn tới tệp 'top50.csv' trên Google Colab
file_path = '/content/top50.csv'

# Đọc tệp 'top50.csv' vào DataFrame
df = pd.read_csv(file_path, encoding='ISO-8859-1')

# # Hiển thị thông tin của DataFrame
# print(df.info())

# # Hiển thị một số hàng đầu tiên của DataFrame
# print(df.head(50))

# # Hiển thị DataFrame thành bảng
# display(df)

# # Kiểm tra các biển trong tập dữ liệu
# print(df.describe())

# #Xác minh các giá trị còn thiếu trong tập dữ liệu:
# print(df.isnull().sum())

# # Tổng quan thống kê
# print(df.describe(include='object'))  # Các cột phân loại
# print(df.describe(include=np.number)) # Các cột số

# # Kiểm tra dữ liệu trùng lặp
# print(df.duplicated().sum())

# # Đổi tên các cột
# df.rename(columns={'Acousticness..':'Acousticness','Loudness..dB..':'Loudness_dB','Speechiness.':'Speechiness',
#                    'Beats.Per.Minute':'Beats_Per_Minute','Track.Name':'Track_Name','Artist.Name':'Artist_Name',
#                    'Length.': 'Length','Valence.':'Valence'}, inplace=True)
# # Hiển thị một số hàng đầu tiên của DataFrame
# print(df.head(50))

# #Artist Name analysis
# print(df['Artist.Name'].value_counts())

# # Analysis of Genre
# print(df['Genre'].value_counts())

# # Hiển thị DataFrame thành bảng
# display(df)

# #Sorting of Genres and analysis

# main_genres = ['hip hop','jazz','reggae','techno','trap','regga','rap','r&b','rock','pop','blues']
# def check_genre(sir):
#     for word in main_genres:
#         if sir.find(word) != -1:
#             if word == 'rap':
#                 return 'hip hop'
#             else:
#                 return word
#     return sir

# df['Main_Genre'] = df['Genre'].apply(check_genre)
# print(df['Main_Genre'].value_counts())

# # Linear and Non-linear trendline for beat per minute
# px.scatter(df,x='Beats_Per_Minute', trendline="ols", trendline_options=dict(log_x=True),trendline_scope="overall",title='Linear trendline for beat per minute')
# px.scatter(df,x='Danceability', trendline="expanding",trendline_scope="overall",title='Non-linear trendline for Danceability')